name: create a comment on new issues

on: 
  issues:
    types: [opened]
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:

  comment-with-api:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
     - name: Create comment with API
       run: |
         gh api -X POST \
           http://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='
            Comment but from API Call not action
            '
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORGANIZATION: ${{ github.event.repository.owner.login }} #JSON structure changed
        REPOSITORY: ${{ github.event.repository.name }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
